import type { User, Store, Listing, Order } from './types';

// Note: This is a mock database. In a real application, this data would be stored
// in a database like Firestore and fetched via API calls. Changes made during
// runtime (like new user signups) will only persist for the current session.

export let mockUsers: User[] = [
  { id: 'user-1', name: 'Active Andy', email: 'active@test.com', avatar: 'https://picsum.photos/seed/user1/100/100', status: 'ACTIVE', storeId: 'store-1' },
  { id: 'user-2', name: 'Limited Lisa', email: 'limited@test.com', avatar: 'https://picsum.photos/seed/user2/100/100', status: 'LIMITED', storeId: 'store-2' },
  { id: 'user-3', name: 'Suspended Sam', email: 'suspended@test.com', avatar: 'https://picsum.photos/seed/user3/100/100', status: 'SUSPENDED' },
];

export const mockStores: Store[] = [
  {
    id: 'store-1',
    name: 'Galactic Treasures',
    url: 'galactic-treasures',
    logo: 'https://picsum.photos/seed/store1/200/200',
    about: 'Your one-stop shop for collectibles from across the galaxy. We specialize in rare trading cards and interstellar artifacts.',
    ownerId: 'user-1',
    paymentMethods: { paypal: 'paypal.me/galactic', venmo: '@galactic-treasures' },
  },
  {
    id: 'store-2',
    name: 'Retro Rewind',
    url: 'retro-rewind',
    logo: 'https://picsum.photos/seed/store2/200/200',
    about: 'Bringing back the 80s and 90s! Find vintage toys, games, and memorabilia that will take you on a trip down memory lane.',
    ownerId: 'user-2',
    paymentMethods: { paypal: 'paypal.me/retro' },
  },
];

export const mockListings: Listing[] = [
  {
    id: 'listing-1',
    title: 'Holographic Charizard Card',
    category: 'Trading Cards',
    description: 'First edition, mint condition holographic Charizard. A must-have for any serious collector.',
    price: 499.99,
    condition: 'New',
    quantity: 1,
    images: ['https://picsum.photos/seed/list1/600/400'],
    tags: ['pokemon', 'rare', 'holographic'],
    storeId: 'store-1',
    createdAt: '2023-10-26T10:00:00Z',
  },
  {
    id: 'listing-2',
    title: 'Vintage Star Wars Action Figure',
    category: 'Action Figures',
    description: 'Original 1977 Luke Skywalker action figure with telescoping lightsaber. In original packaging.',
    price: 850.0,
    condition: 'Like New',
    quantity: 1,
    images: ['https://picsum.photos/seed/list2/600/400'],
    tags: ['star wars', 'vintage', 'kenner'],
    storeId: 'store-2',
    createdAt: '2023-10-25T11:30:00Z',
  },
  {
    id: 'listing-3',
    title: 'The Amazing Spider-Man #1',
    category: 'Comics',
    description: 'A near-mint copy of The Amazing Spider-Man #1. Graded 9.4 by CGC.',
    price: 12000.0,
    condition: 'Like New',
    quantity: 1,
    images: ['https://picsum.photos/seed/list3/600/400'],
    tags: ['marvel', 'spider-man', 'first issue'],
    storeId: 'store-1',
    createdAt: '2023-10-24T14:00:00Z',
  },
  {
    id: 'listing-4',
    title: 'Signed Blade Runner Poster',
    category: 'Memorabilia',
    description: 'Original movie poster for Blade Runner (1982), signed by Harrison Ford. Comes with certificate of authenticity.',
    price: 2500.0,
    condition: 'Used',
    quantity: 1,
    images: ['https://picsum.photos/seed/list4/600/400'],
    tags: ['movie', 'autograph', 'sci-fi'],
    storeId: 'store-2',
    createdAt: '2023-10-23T09:00:00Z',
  },
   {
    id: 'listing-5',
    title: 'NES Zelda Gold Cartridge',
    category: 'Video Games',
    description: 'The Legend of Zelda for NES, rare gold cartridge edition. Game works perfectly, some wear on the label.',
    price: 75.0,
    condition: 'Used',
    quantity: 3,
    images: ['https://picsum.photos/seed/list5/600/400'],
    tags: ['nintendo', 'zelda', 'retro'],
    storeId: 'store-1',
    createdAt: '2023-10-22T18:00:00Z',
  },
  {
    id: 'listing-6',
    title: 'Inverted Jenny Stamp',
    category: 'Stamps',
    description: 'A high-quality replica of the famous Inverted Jenny postage stamp. A centerpiece for any collection.',
    price: 50.0,
    condition: 'New',
    quantity: 10,
    images: ['https://picsum.photos/seed/list6/600/400'],
    tags: ['philately', 'rare', 'replica'],
    storeId: 'store-2',
    createdAt: '2023-10-21T12:45:00Z',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    listingId: 'listing-1',
    listingTitle: 'Holographic Charizard Card',
    listingImage: 'https://picsum.photos/seed/list1/600/400',
    buyerId: 'user-2',
    sellerId: 'user-1',
    quantity: 1,
    totalPrice: 499.99,
    status: 'Shipped',
    shippingAddress: '123 Collector Lane, Hobbytown, HT 54321',
    trackingNumber: '1Z999AA10123456784',
    carrier: 'UPS',
    createdAt: '2023-10-27T10:00:00Z',
  },
    {
    id: 'order-2',
    listingId: 'listing-4',
    listingTitle: 'Signed Blade Runner Poster',
    listingImage: 'https://picsum.photos/seed/list4/600/400',
    buyerId: 'user-1',
    sellerId: 'user-2',
    quantity: 1,
    totalPrice: 2500.0,
    status: 'Pending Payment',
    createdAt: '2023-10-28T11:00:00Z',
  },
];
